spring:
  profiles:
    active: dev
  application:
    name: basket-service
  cloud:
    config:
      uri: http://localhost:8888/
      label: dev/Muhammadamin
  config:
    import: optional:configserver:http://localhost:8888/